
import pandas as pd
import numpy as np

# Load the dataset generated by MuJoCo
df = pd.read_csv("mujoco_workspace_dataset.csv")

print("MuJoCo dataset loaded successfully!")

print("\nDataset shape:")
print(df.shape)

print("\nDataset columns:")
print(df.columns.tolist())

print("\nFirst 5 samples:")
print(df.head())

print("\nDataset information:")
print(df.info())

# Separate inputs and outputs
X = df[["q1_rad", "q2_rad"]]
Y = df[["x_m", "y_m"]]

print("\nInput shape:", X.shape)
print("Output shape:", Y.shape)

from sklearn.model_selection import train_test_split

# Split the MuJoCo dataset into training and testing data
X_train, X_test, Y_train, Y_test = train_test_split(
    X,
    Y,
    test_size=0.2,
    random_state=42
)

print("\nTraining samples:", len(X_train))
print("Testing samples:", len(X_test))

print("\nTraining input shape:", X_train.shape)
print("Testing input shape:", X_test.shape)

print("Training output shape:", Y_train.shape)
print("Testing output shape:", Y_test.shape)

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score

# Create Random Forest model
model = RandomForestRegressor(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

# Train the model
model.fit(X_train, Y_train)

print("\nRandom Forest training completed!")

# Predict end-effector positions for the test data
Y_pred = model.predict(X_test)

# Calculate errors
mae = mean_absolute_error(Y_test, Y_pred)
r2 = r2_score(Y_test, Y_pred)

print("\nModel Performance:")
print("MAE:", mae, "m")
print("MAE:", mae * 1000, "mm")
print("R²:", r2)

# Test the trained ML model on a new joint configuration

q1_test_deg = 45
q2_test_deg = 30

# Convert degrees to radians
q1_test = np.deg2rad(q1_test_deg)
q2_test = np.deg2rad(q2_test_deg)

# Create input for the ML model
new_configuration = pd.DataFrame({
    "q1_rad": [q1_test],
    "q2_rad": [q2_test]
})

# ML prediction
ml_prediction = model.predict(new_configuration)[0]

print("\n=== New Configuration Test ===")
print("q1:", q1_test_deg, "degrees")
print("q2:", q2_test_deg, "degrees")

print("\nML predicted position:")
print("X:", ml_prediction[0], "m")
print("Y:", ml_prediction[1], "m")

# Compare ML prediction with MuJoCo ground truth

# Load MuJoCo model
import mujoco

xml = """
<mujoco model="two_link_arm">

    <worldbody>

        <body name="link1" pos="0 0 0.05">

            <joint
                name="joint1"
                type="hinge"
                pos="0 0 0"
                axis="0 0 1"
            />

            <geom
                name="link1_geom"
                type="capsule"
                fromto="0 0 0 0.30 0 0"
                size="0.025"
            />

            <body name="link2" pos="0.30 0 0">

                <joint
                    name="joint2"
                    type="hinge"
                    pos="0 0 0"
                    axis="0 0 1"
                />

                <geom
                    name="link2_geom"
                    type="capsule"
                    fromto="0 0 0 0.15 0 0"
                    size="0.022"
                />

                <site
                    name="end_effector"
                    pos="0.15 0 0"
                    size="0.03"
                />

            </body>

        </body>

    </worldbody>

</mujoco>
"""

mujoco_model = mujoco.MjModel.from_xml_string(xml)
mujoco_data = mujoco.MjData(mujoco_model)

# Set the same joint configuration
mujoco_data.qpos[0] = q1_test
mujoco_data.qpos[1] = q2_test

# Calculate MuJoCo kinematics
mujoco.mj_forward(mujoco_model, mujoco_data)

# Read MuJoCo ground truth
mujoco_position = mujoco_data.site_xpos[0]

# Calculate errors
x_error = abs(ml_prediction[0] - mujoco_position[0])
y_error = abs(ml_prediction[1] - mujoco_position[1])

position_error = np.sqrt(
    x_error**2 + y_error**2
)

print("\nMuJoCo ground truth:")
print("X:", mujoco_position[0], "m")
print("Y:", mujoco_position[1], "m")

print("\nPrediction error:")
print("X error:", x_error * 1000, "mm")
print("Y error:", y_error * 1000, "mm")
print("Overall position error:", position_error * 1000, "mm")

# Generate completely new joint configurations
np.random.seed(123)

n_new_tests = 1000

q1_new = np.random.uniform(-np.pi, np.pi, n_new_tests)
q2_new = np.random.uniform(-np.pi, np.pi, n_new_tests)

new_inputs = pd.DataFrame({
    "q1_rad": q1_new,
    "q2_rad": q2_new
})

print("\n=== New Generalization Test ===")
print("New configurations:", len(new_inputs))
print("New input shape:", new_inputs.shape)

# Generate MuJoCo ground truth for the new configurations

new_x = np.zeros(n_new_tests)
new_y = np.zeros(n_new_tests)

# Create MuJoCo model
mujoco_xml = """
<mujoco model="two_link_arm">

    <worldbody>

        <body name="link1" pos="0 0 0.05">

            <joint
                name="joint1"
                type="hinge"
                pos="0 0 0"
                axis="0 0 1"
            />

            <geom
                name="link1_geom"
                type="capsule"
                fromto="0 0 0 0.30 0 0"
                size="0.025"
            />

            <body name="link2" pos="0.30 0 0">

                <joint
                    name="joint2"
                    type="hinge"
                    pos="0 0 0"
                    axis="0 0 1"
                />

                <geom
                    name="link2_geom"
                    type="capsule"
                    fromto="0 0 0 0.15 0 0"
                    size="0.022"
                />

                <site
                    name="end_effector"
                    pos="0.15 0 0"
                    size="0.03"
                />

            </body>

        </body>

    </worldbody>

</mujoco>
"""

new_model = mujoco.MjModel.from_xml_string(mujoco_xml)
new_data = mujoco.MjData(new_model)

# Simulate all 1000 new configurations
for i in range(n_new_tests):

    new_data.qpos[0] = q1_new[i]
    new_data.qpos[1] = q2_new[i]

    mujoco.mj_forward(new_model, new_data)

    new_x[i] = new_data.site_xpos[0][0]
    new_y[i] = new_data.site_xpos[0][1]

print("\nMuJoCo ground truth generated successfully!")
print("Ground truth shape:", (len(new_x), 2))

# Predict the 1000 new configurations using Random Forest

new_predictions = model.predict(new_inputs)

# Separate predicted X and Y
predicted_x = new_predictions[:, 0]
predicted_y = new_predictions[:, 1]

print("\nRandom Forest predictions generated successfully!")
print("Prediction shape:", new_predictions.shape)

print("\nFirst 5 comparisons:")

for i in range(5):
    print(
        f"Sample {i}: "
        f"MuJoCo = ({new_x[i]:.6f}, {new_y[i]:.6f}) m | "
        f"ML = ({predicted_x[i]:.6f}, {predicted_y[i]:.6f}) m"
    )

# Calculate generalization performance

from sklearn.metrics import mean_absolute_error, r2_score

# Create ground-truth array
new_ground_truth = np.column_stack((new_x, new_y))

# Overall MAE
generalization_mae = mean_absolute_error(
    new_ground_truth,
    new_predictions
)

# R²
generalization_r2 = r2_score(
    new_ground_truth,
    new_predictions
)

# X and Y MAE separately
x_mae = mean_absolute_error(
    new_x,
    predicted_x
)

y_mae = mean_absolute_error(
    new_y,
    predicted_y
)

# Euclidean position error for every sample
position_errors = np.sqrt(
    (predicted_x - new_x)**2 +
    (predicted_y - new_y)**2
)

mean_position_error = np.mean(position_errors)
max_position_error = np.max(position_errors)

print("\n=== 1000-Pose Generalization Results ===")

print("\nX MAE:", x_mae, "m")
print("X MAE:", x_mae * 1000, "mm")

print("\nY MAE:", y_mae, "m")
print("Y MAE:", y_mae * 1000, "mm")

print("\nOverall MAE:", generalization_mae, "m")
print("Overall MAE:", generalization_mae * 1000, "mm")

print("\nR²:", generalization_r2)

print("\nMean position error:",
      mean_position_error * 1000, "mm")

print("Maximum position error:",
      max_position_error * 1000, "mm")
